services:
  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=webrust
      - POSTGRES_USER=webuser
      - POSTGRES_PASSWORD="One1-Two2-Three3-Four4"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=galkaev
    depends_on:
      - db

volumes:
  db-data:

    